metadata:
  name: provider
kind: Deployment
spec:
  template:
    metadata:
      name: provider
      namespace: default
      labels:
        container: provider
        project: provider
    spec:
      containers:
      - image: chungsju/provider
        imagePullPolicy: Always
        name: provider
        env:
        - name: BW_APP_MONITORING_CONFIG
          value: '{"url":"http://bwce-mon-svc:8080"}'
        - name: PROVIDER_PORT
          value: '8000'
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: BW_PROFILE
          value: Docker
        ports:
        - containerPort: 8000
  replicas: 1
  selector:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
