metadata:
  name: provider-svc
  namespace: default
  labels:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
kind: Service
spec:
  selector:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 32180
